name: Test OS-Specific Python Caching by Docker (Reverse Order)

on:
  workflow_dispatch:

jobs:
  ubuntu-24-04:
    runs-on: [self-hosted]
    container:
      image: ubuntu:24.04
    name: Run inside Ubuntu 24.04 container
    steps:
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl build-essential libssl-dev libffi-dev python3-pip lsb-release

      - name: Clear _work directory
        run: |
          echo "Clearing the _work directory to ensure a fresh Python installation..."
          rm -rf /_work/

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Verify Python Version
        run: |
          echo "Python: $(python --version)"
          echo "OS:"
          cat /etc/os-release

  ubuntu-20-04:
    needs: ubuntu-24-04
    runs-on: [self-hosted]
    container:
      image: ubuntu:20.04
    name: Run inside Ubuntu 20.04 container
    steps:
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl build-essential libssl-dev libffi-dev python3-pip lsb-release
      
      - name: Install Required Dependencies
        run: |
          apt-get update
          apt-get install -y gawk bison
          
      - name: Upgrade glibc
        run: |
          apt-get update
          apt-get install -y wget
          wget http://ftp.gnu.org/gnu/libc/glibc-2.38.tar.gz
          tar -xvzf glibc-2.38.tar.gz
          cd glibc-2.38
          mkdir build
          cd build
          ../configure --prefix=/usr
          make -j$(nproc)
          make install
          cd ../..
          rm -rf glibc-2.38 glibc-2.38.tar.gz
          
      - name: Fix pip cache permissions
        run: |
          mkdir -p /github/home/.cache/pip
          chown -R $(whoami) /github/home/.cache

      - name: Clear _work directory
        run: |
          echo "Clearing the _work directory to ensure a fresh Python installation..."
          rm -rf /_work/

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Verify Python Version
        run: |
          echo "Python: $(python --version)"
          echo "OS:"
          cat /etc/os-release
