name: Python caching from Ubuntu 24 to 22

on:
  workflow_dispatch:

jobs:
  ubuntu-24-04:
    runs-on: [self-hosted]
    container:
      image: ubuntu:24.04
    name: Run inside Ubuntu 24.04 container
    steps:
      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl build-essential libssl-dev libffi-dev python3-pip lsb-release

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Verify Python Version
        run: |
          echo "Python: $(python --version)"
          echo "OS:"
          cat /etc/os-release

  ubuntu-22-04:
    needs: ubuntu-24-04
    runs-on: [self-hosted]
    container:
      image: ubuntu:22.04
    name: Run inside Ubuntu 22.04 container
    steps:

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y curl build-essential libssl-dev libffi-dev python3-pip lsb-release
          
      - name: Fix pip cache permissions
        run: |
          mkdir -p /github/home/.cache/pip
          chown -R $(whoami) /github/home/.cache

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Verify Python Version
        run: |
          echo "Python: $(python --version)"
          echo "OS:"
          cat /etc/os-release
