name: Reproduce Verbose Output Issue with Dynamic Python Version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to set up (e.g., 3.9, 3.10, etc.)'
        required: true
        default: '3.7.15'

jobs:
  test-verbose-output:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Display Environment Variables
        run: |
          Get-ChildItem Env: | Sort-Object Name

      # - name: Clear Cached Python
      #   run: |
      #     $pythonCachePath = "$env:AGENT_TOOLSDIRECTORY\Python\${{ github.event.inputs.python-version }}.*"
      #     if (Test-Path $pythonCachePath) {
      #         Remove-Item -Recurse -Force $pythonCachePath
      #         Write-Host "Cleared cached Python ${{ github.event.inputs.python-version }}."
      #     } else {
      #         Write-Host "No cached Python ${{ github.event.inputs.python-version }} found to clear."
      #     }

      - name: Set up Python (Fresh Download)
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ github.event.inputs.python-version }}
