name: Reproduce Verbose Output Issue

on:
  workflow_dispatch:

jobs:
  test-verbose-output:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
