name: Reproduce Verbose Output Issue with Dynamic Python Version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to set up (e.g., 3.9, 3.10, etc.)'
        required: true
        default: '3.14.0-alpha.7'

jobs:
  test-verbose-output:
    runs-on: windows-latest

    steps:
      - name: Checkout python-versions
        uses: actions/checkout@v3

      - name: Set up Python (Fresh Download)
        uses: chiranjib-swain/setup-python@test-1097
        with:
          python-version: ${{ github.event.inputs.python-version }}
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          architecture: 'arm64'
          # freethreaded: 'true'
