name: Check directories

on:
  workflow_dispatch:
jobs:
  ubuntu-24-04:
    runs-on: [self-hosted]
    container:
      image: ubuntu:24.04
    name: Run inside Ubuntu 24.04 container
    steps:
      # - name: Install deps
      #   run: |
      #     apt-get update
      #     apt-get install -y curl build-essential libssl-dev libffi-dev python3-pip lsb-release

      - name: List Directories in Root
        run: |
          echo "Listing all directories and files in the root:"
          ls -lah /

      - name: Remove Cached Python Installation
        run: |
          echo "Removing cached Python installation..."
          rm -rf /_work/_tool/Python
